#include "ui/ConfigUiRegistry.h"

#include <string>

void ConfigUiRegistry::Register(const std::string& name, EffectUiDraw draw)
{
    m_draws[name] = std::move(draw);
}

const EffectUiDraw* ConfigUiRegistry::Find(const std::string& name) const
{
    auto it = m_draws.find(name);
    return it == m_draws.end() ? nullptr : &it->second;
}

// ── Central registration ──────────────────────────────────────────────────────
// One forward declaration + call per effect UI file (see src/ui/effects/).
#define EFFECT_UI(Name) void Register##Name##UI(ConfigUiRegistry&);
EFFECT_UI(AddBorders)
EFFECT_UI(BufferSave)
EFFECT_UI(ChannelShift)
EFFECT_UI(Clear)
EFFECT_UI(Strobe)
EFFECT_UI(Grain)
EFFECT_UI(Invert)
EFFECT_UI(Scatter)
EFFECT_UI(UniqueTone)
EFFECT_UI(EffectList)
EFFECT_UI(FadeOut)
EFFECT_UI(MovingParticle)
EFFECT_UI(Movement)
EFFECT_UI(Starfield)
EFFECT_UI(Simple)
EFFECT_UI(Mosaic)
EFFECT_UI(FastBrightness)
EFFECT_UI(Mirror)
EFFECT_UI(Blur)
EFFECT_UI(ColorReduction)
EFFECT_UI(ColorClip)
EFFECT_UI(BlitEffect)
EFFECT_UI(RotoBlitter)
EFFECT_UI(ColorFade)
EFFECT_UI(SetRenderMode)
EFFECT_UI(SuperScope)
EFFECT_UI(Interferences)
EFFECT_UI(Interleave)
EFFECT_UI(MultiFilter)
EFFECT_UI(Multiplier)
EFFECT_UI(OnBeatClear)
EFFECT_UI(Bump)
EFFECT_UI(Water)
EFFECT_UI(WaterBump)
EFFECT_UI(DotGrid)
EFFECT_UI(BassSpin)
EFFECT_UI(Normalize)
EFFECT_UI(ColorModifier)
EFFECT_UI(RotatingStars)
EFFECT_UI(OscilloscopeStar)
EFFECT_UI(Ring)
EFFECT_UI(Picture)
EFFECT_UI(Picture2)
EFFECT_UI(Convolution)
EFFECT_UI(ColorMap)
EFFECT_UI(Ramp)
EFFECT_UI(CustomBpm)
EFFECT_UI(DynamicDistanceModifier)
EFFECT_UI(DynamicShift)
EFFECT_UI(Texer)
EFFECT_UI(Texer2)
EFFECT_UI(ImageGrid)
EFFECT_UI(MultiDelay)
EFFECT_UI(Triangle)
EFFECT_UI(VideoDelay)
EFFECT_UI(DynamicMovement)
EFFECT_UI(DotFountain)
EFFECT_UI(DotPlane)
EFFECT_UI(Timescope)
EFFECT_UI(Brightness)
EFFECT_UI(Text)
#undef EFFECT_UI

void RegisterAllEffectUis(ConfigUiRegistry& reg)
{
#define EFFECT_UI(Name) Register##Name##UI(reg);
    EFFECT_UI(AddBorders)
    EFFECT_UI(BufferSave)
    EFFECT_UI(ChannelShift)
    EFFECT_UI(Clear)
    EFFECT_UI(Strobe)
    EFFECT_UI(Grain)
    EFFECT_UI(Invert)
    EFFECT_UI(Scatter)
    EFFECT_UI(UniqueTone)
    EFFECT_UI(EffectList)
    EFFECT_UI(FadeOut)
    EFFECT_UI(MovingParticle)
    EFFECT_UI(Movement)
    EFFECT_UI(Starfield)
    EFFECT_UI(Simple)
    EFFECT_UI(Mosaic)
    EFFECT_UI(FastBrightness)
    EFFECT_UI(Mirror)
    EFFECT_UI(Blur)
    EFFECT_UI(ColorReduction)
    EFFECT_UI(ColorClip)
    EFFECT_UI(BlitEffect)
    EFFECT_UI(RotoBlitter)
    EFFECT_UI(ColorFade)
    EFFECT_UI(SetRenderMode)
    EFFECT_UI(SuperScope)
    EFFECT_UI(Interferences)
    EFFECT_UI(Interleave)
    EFFECT_UI(MultiFilter)
    EFFECT_UI(Multiplier)
    EFFECT_UI(OnBeatClear)
    EFFECT_UI(Bump)
    EFFECT_UI(Water)
    EFFECT_UI(WaterBump)
    EFFECT_UI(DotGrid)
    EFFECT_UI(BassSpin)
    EFFECT_UI(Normalize)
    EFFECT_UI(ColorModifier)
    EFFECT_UI(RotatingStars)
    EFFECT_UI(OscilloscopeStar)
    EFFECT_UI(Ring)
    EFFECT_UI(Picture)
    EFFECT_UI(Picture2)
    EFFECT_UI(Convolution)
    EFFECT_UI(ColorMap)
    EFFECT_UI(Ramp)
    EFFECT_UI(CustomBpm)
    EFFECT_UI(DynamicDistanceModifier)
    EFFECT_UI(DynamicShift)
    EFFECT_UI(Texer)
    EFFECT_UI(Texer2)
    EFFECT_UI(ImageGrid)
    EFFECT_UI(MultiDelay)
    EFFECT_UI(Triangle)
    EFFECT_UI(VideoDelay)
    EFFECT_UI(DynamicMovement)
    EFFECT_UI(DotFountain)
    EFFECT_UI(DotPlane)
    EFFECT_UI(Timescope)
    EFFECT_UI(Brightness)
    EFFECT_UI(Text)
#undef EFFECT_UI
}
